### ISSUE TITLE
关于 Go 包中文翻译文档的目录规划

### ISSUE THREAD

**Issue by achun** [golang-china/golangdoc.translations#7]
目标: 让 golang-china 成为Go 包中文翻译文档 github 中心.
这需要考虑目录规划, 问题比较复杂, 这里先罗列一下已知的事实和问题.
## 事实
1. 不管源码是否托管于 github, 不影响把翻译放到 golang-china.
2. 标准包没有前缀 host 路径
## 问题
1. git 托管地址和 import 地址可能不同.
2. 尽可能简化翻译目录和 import 地址的对应算法
3. 官方 blog 翻译不属于 package

期望讨论出简单的翻译文档目录规划方式.

**Comment by achun** [comment]
以 import path 中的 host 部分作为仓库名,创建到 golang-china 下.
如果 import path 的路径是 github.com, 那么省略 github.com, 直接使用 user 名.
比如 import path:

    github.com/google/go-github/github

对应创建

    golang-china/google/go-github/github

 import path:

    golang.org/x/tools/blog

对应创建

    golang-china/golang.org/x/tools/blog

**Comment by chai2010** [comment]
我感觉按照多个 gopath 的思路整理也不错:

1. `golang.org/src/...`, 对应全部 Go 和 Google 维护的半官方扩展 (含托管在 github 的项目), 这个属于 API 比较稳定的 标准库+标准扩展库
2. `github.com/src/...`, 对应 github 上的普通项目
3. `bitbucket.org/src/...`, 同上

PS: 如果每个项目对应一个项目, 会导致项目很多, 不好管理.

**Comment by achun** [comment]
@chai2010 
确实, 多个 gopath 的思路解决了项目过多的问题.
src 这个目录是为了支持 blog , 把源码和文章啥的分开么?
如果有这个作用, 那么没有问题, 如果不是的话, 请明确 src 的具体作用.

另外: 如果这个方式是和 import path 对应的, 不适合把官方 std和 google 维护的包置于 golang.org/src/ 之下. std 应该独立

**Comment by chai2010** [comment]
我比较倾向简单的组织方式, 就2个目录:

1. 目录1, 对应翻译的核心文件(必备), 包含标准库翻译和半官方的包翻译
2. 目录2, 对应其他的翻译, 这个目录比较自由, 可以放任意的包翻译(前提是包的路径比较稳定, fork包一般不包含), 类似 Python 的 `site-packages` 目录.
3. 当然, 还可以有目录3/4/n, 但那是用户自己的自由了...

**Comment by chai2010** [comment]
`src` 的目的是为了和Go的目录结构同步, 同时比较方便区分 blog/talk/tour 之类的翻译文件.

我感觉 `golang-china/src` 的名字的含义不明确(名字尽量稳定可能会有很多好处),

而且前面说到的 `目录1` 和 `目录2`, 再对应稳定的名字, 我们可以方便地做翻译文件的安装脚本.
普通用户可能不会关心太复杂的翻译目录结构, 他们只是想方便地使用翻译后的文档.
